[package]
name = "moco-job"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
moco-core = { workspace = true }
facet = { workspace = true }
facet-styx = { workspace = true }
